#!/usr/bin/env bash

PLCC_GIT_BRANCH=v8.0.1 /bin/bash -c "$(curl -fsSL https://github.com/ourPLCC/plcc/raw/main/installers/plcc/install.bash)" >> "$HOME/.bashrc"

git clone https://github.com/ourPLCC/languages
rm -rf languages/.git
echo "*" > languages/.gitignore
